events {
    worker_connections 1024;
}

http {
    # Daftar 3 kembaran server Laravel kita
    upstream laravel_cluster {
        server backend1:8000;
        server backend2:8000;
        server backend3:8000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://laravel_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # FITUR RAHASIA UNTUK PRESENTASI:
            # Ini akan memunculkan tulisan di browser untuk membuktikan server mana yang merespons
            add_header X-Served-By $upstream_addr always;
        }
    }
}